Upgrade chevrotain and resolve GraphQL parser ambiguities
stardog-union/millan pull request #56
Opened 2020-12-14 18:35 UTC by jmrog

As of chevrotain v4.7.0, the hierarchy of token categories is taken into consideration when a parser performs self-analysis. This reveals ambiguities in the parse rules for our GraphQL grammars. Since, in GraphQL, many tokens count as `Name` tokens, and since the `Name` category token is now taken into consideration by chevrotain during self-analysis, there are a number of duplicate prefix paths through the grammar.

This PR resolve the ambiguities (with a result being that our parsers can work with chevrotain v4.7.0+). The ambiguities are resolved by removing some special Stardog-specific additions to GraphQL from the _syntax_ level of the `StardogGraphQlParser`, and instead Stardog-specific additions (e.g., embedded SPARQL syntax) to the `StardogGraphQlVisitor` that is employed _after_ the parse phase. Currently, removing the additions from the syntax/parse level _does_ have a negative side effect, in that it eliminates some nice auto-completion for Stardog-specific GraphQL that we had working previously. To get that back, we'll have to move additional logic to the `StardogGraphQlVisitor`, but that will take some work.

2020-12-14 20:22 UTC, joshhk72 reviewed
Quick comment only

2020-12-18 21:19 UTC, cchaffatt reviewed
looked over briefly and will dive deeper in once out of draft.

chevrotain documentation now recommends we use perform self analysis as:
```
this.performSelfAnalysis()
```
and looks like they deprecated `Parser`.

Not necessary changes as of now but perhaps painless things we can add at the end.

2021-02-04 18:19 UTC, joshhk72 requested changes
I think things look good, all the prior features seem intact and new errors for directives seem to work pretty well. Few questions/comments for now

2021-02-04 18:23 UTC, joshhk72 commented on src/graphql/StardogGraphQlVisitor.ts
> +  ...validatorOptions
Maybe it's better to just pass in `validatorOptions` as its own object

2021-02-04 18:38 UTC, jmrog commented on src/graphql/StardogGraphQlVisitor.ts
> +    .map((argumentTokenType) => `\`${argumentTokenType.PATTERN}\``)
This was _mostly_ just personal preference, but not entirely; the Monaco editor can also display markdown. We may want to use that feature on the Studio side to show the language keywords with special formatting. But I"m not wed to that idea, so could remove here if we want.

2021-02-04 18:41 UTC, jmrog commented on src/graphql/StardogGraphQlVisitor.ts
> +        return;
Yes, you're right; I think this comment is a leftover that should have been removed when I refactored. I'll update it.

Re: the tangential question: yes. :)

2021-02-04 18:44 UTC, jmrog commented on src/graphql/StardogGraphQlVisitor.ts
> +        !directiveNameToken ||
Yep, this is also a leftover thing from refactoring. Removing.

2021-02-04 18:56 UTC, joshhk72 commented on src/graphql/StardogGraphQlVisitor.ts
> +    .map((argumentTokenType) => `\`${argumentTokenType.PATTERN}\``)
Seems good as it is.

2021-02-10 15:10 UTC, joshhk72 approved these changes
LGTM, but want to take a quick look again

2021-02-10 15:47 UTC, joshhk72 commented
LGTM (again) on second glance through

2021-02-16 18:25 UTC, merged